
package principal;

import utils.Persona;


public class VentanaEditar extends javax.swing.JFrame {
    
    Persona persona;
    String texto;
    TablaBotones ventana;
    
    public VentanaEditar(TablaBotones tabla,Persona persona) {
        this.ventana = tabla;
        this.texto = texto;
        this.persona = persona;
        initComponents();
        componentes();
    }

    public void componentes(){
        
        setTitle(" Confirmación de eliminación ");
        
        etiqueta_texto.setText(texto);
        setVisible(true);
        setLocationRelativeTo(null);
        setResizable(false);
        revalidate();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
        campo_Documento.setText(persona.getDocumento());
        campo_Nombres.setText(persona.getNombres());
        campo_Apellidos.setText(persona.getApellidos());
        campo_Telefono.setText(persona.getTelefono());
        campo_Correo.setText(persona.getCorreo());
        
        ventana.imprimirPersonas();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        etiqueta_texto = new javax.swing.JLabel();
        contenedor_Formulario17 = new javax.swing.JPanel();
        etiqueta_Documento17 = new javax.swing.JLabel();
        campo_documento1 = new javax.swing.JTextField();
        etiqueta_Nombres17 = new javax.swing.JLabel();
        campon_nombre = new javax.swing.JTextField();
        etiqueta_Apellidos17 = new javax.swing.JLabel();
        campo_apellidos = new javax.swing.JTextField();
        etiqueta_Telefono17 = new javax.swing.JLabel();
        campo_telefono = new javax.swing.JTextField();
        etiqueta_Correo17 = new javax.swing.JLabel();
        campo_correo = new javax.swing.JTextField();
        botonCancelar = new javax.swing.JToggleButton();
        BotonAgregar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setForeground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edicion");

        etiqueta_texto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiqueta_texto.setForeground(new java.awt.Color(255, 255, 255));
        etiqueta_texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(etiqueta_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiqueta_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        contenedor_Formulario17.setBackground(new java.awt.Color(102, 204, 255));

        etiqueta_Documento17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Documento17.setText("Documento:");

        campo_documento1.setToolTipText("");

        etiqueta_Nombres17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Nombres17.setText("Nombres:");

        campon_nombre.setToolTipText("");

        etiqueta_Apellidos17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Apellidos17.setText("Apellidos:");

        campo_apellidos.setToolTipText("");

        etiqueta_Telefono17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Telefono17.setText("Telefono:");

        campo_telefono.setToolTipText("");

        etiqueta_Correo17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Correo17.setText("Correo Elct:");

        campo_correo.setToolTipText("");

        botonCancelar.setBackground(new java.awt.Color(102, 102, 255));
        botonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        botonCancelar.setText("CANCELAR");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        BotonAgregar.setBackground(new java.awt.Color(0, 204, 51));
        BotonAgregar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BotonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BotonAgregar.setText("AGREGAR");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenedor_Formulario17Layout = new javax.swing.GroupLayout(contenedor_Formulario17);
        contenedor_Formulario17.setLayout(contenedor_Formulario17Layout);
        contenedor_Formulario17Layout.setHorizontalGroup(
            contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedor_Formulario17Layout.createSequentialGroup()
                .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedor_Formulario17Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenedor_Formulario17Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(BotonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenedor_Formulario17Layout.createSequentialGroup()
                                .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiqueta_Documento17, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo_documento1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiqueta_Nombres17, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campon_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiqueta_Apellidos17, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(contenedor_Formulario17Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiqueta_Telefono17, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiqueta_Correo17, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contenedor_Formulario17Layout.setVerticalGroup(
            contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedor_Formulario17Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedor_Formulario17Layout.createSequentialGroup()
                            .addComponent(etiqueta_Apellidos17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(contenedor_Formulario17Layout.createSequentialGroup()
                            .addComponent(etiqueta_Nombres17)
                            .addGap(1, 1, 1)))
                    .addGroup(contenedor_Formulario17Layout.createSequentialGroup()
                        .addComponent(etiqueta_Documento17)
                        .addGap(1, 1, 1)))
                .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(campo_documento1)
                    .addComponent(campon_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_apellidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiqueta_Correo17)
                    .addComponent(etiqueta_Telefono17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_telefono)
                    .addComponent(campo_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contenedor_Formulario17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedor_Formulario17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregarActionPerformed

     private VentanaEditar(){
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonAgregar;
    private javax.swing.JToggleButton botonCancelar;
    private javax.swing.JToggleButton boton_agregar;
    private javax.swing.JToggleButton boton_agregar1;
    private javax.swing.JToggleButton boton_agregar10;
    private javax.swing.JToggleButton boton_agregar11;
    private javax.swing.JToggleButton boton_agregar12;
    private javax.swing.JToggleButton boton_agregar13;
    private javax.swing.JToggleButton boton_agregar14;
    private javax.swing.JToggleButton boton_agregar15;
    private javax.swing.JToggleButton boton_agregar16;
    private javax.swing.JToggleButton boton_agregar2;
    private javax.swing.JToggleButton boton_agregar3;
    private javax.swing.JToggleButton boton_agregar4;
    private javax.swing.JToggleButton boton_agregar5;
    private javax.swing.JToggleButton boton_agregar6;
    private javax.swing.JToggleButton boton_agregar7;
    private javax.swing.JToggleButton boton_agregar8;
    private javax.swing.JToggleButton boton_agregar9;
    private javax.swing.JTextField campo_Apellidos;
    private javax.swing.JTextField campo_Apellidos1;
    private javax.swing.JTextField campo_Apellidos10;
    private javax.swing.JTextField campo_Apellidos11;
    private javax.swing.JTextField campo_Apellidos12;
    private javax.swing.JTextField campo_Apellidos13;
    private javax.swing.JTextField campo_Apellidos14;
    private javax.swing.JTextField campo_Apellidos15;
    private javax.swing.JTextField campo_Apellidos16;
    private javax.swing.JTextField campo_Apellidos2;
    private javax.swing.JTextField campo_Apellidos3;
    private javax.swing.JTextField campo_Apellidos4;
    private javax.swing.JTextField campo_Apellidos5;
    private javax.swing.JTextField campo_Apellidos6;
    private javax.swing.JTextField campo_Apellidos7;
    private javax.swing.JTextField campo_Apellidos8;
    private javax.swing.JTextField campo_Apellidos9;
    private javax.swing.JTextField campo_Correo;
    private javax.swing.JTextField campo_Correo1;
    private javax.swing.JTextField campo_Correo10;
    private javax.swing.JTextField campo_Correo11;
    private javax.swing.JTextField campo_Correo12;
    private javax.swing.JTextField campo_Correo13;
    private javax.swing.JTextField campo_Correo14;
    private javax.swing.JTextField campo_Correo15;
    private javax.swing.JTextField campo_Correo16;
    private javax.swing.JTextField campo_Correo2;
    private javax.swing.JTextField campo_Correo3;
    private javax.swing.JTextField campo_Correo4;
    private javax.swing.JTextField campo_Correo5;
    private javax.swing.JTextField campo_Correo6;
    private javax.swing.JTextField campo_Correo7;
    private javax.swing.JTextField campo_Correo8;
    private javax.swing.JTextField campo_Correo9;
    private javax.swing.JTextField campo_Documento;
    private javax.swing.JTextField campo_Documento1;
    private javax.swing.JTextField campo_Documento10;
    private javax.swing.JTextField campo_Documento11;
    private javax.swing.JTextField campo_Documento12;
    private javax.swing.JTextField campo_Documento13;
    private javax.swing.JTextField campo_Documento14;
    private javax.swing.JTextField campo_Documento15;
    private javax.swing.JTextField campo_Documento16;
    private javax.swing.JTextField campo_Documento2;
    private javax.swing.JTextField campo_Documento3;
    private javax.swing.JTextField campo_Documento4;
    private javax.swing.JTextField campo_Documento5;
    private javax.swing.JTextField campo_Documento6;
    private javax.swing.JTextField campo_Documento7;
    private javax.swing.JTextField campo_Documento8;
    private javax.swing.JTextField campo_Documento9;
    private javax.swing.JTextField campo_Nombres;
    private javax.swing.JTextField campo_Nombres1;
    private javax.swing.JTextField campo_Nombres10;
    private javax.swing.JTextField campo_Nombres11;
    private javax.swing.JTextField campo_Nombres12;
    private javax.swing.JTextField campo_Nombres13;
    private javax.swing.JTextField campo_Nombres14;
    private javax.swing.JTextField campo_Nombres15;
    private javax.swing.JTextField campo_Nombres16;
    private javax.swing.JTextField campo_Nombres2;
    private javax.swing.JTextField campo_Nombres3;
    private javax.swing.JTextField campo_Nombres4;
    private javax.swing.JTextField campo_Nombres5;
    private javax.swing.JTextField campo_Nombres6;
    private javax.swing.JTextField campo_Nombres7;
    private javax.swing.JTextField campo_Nombres8;
    private javax.swing.JTextField campo_Nombres9;
    private javax.swing.JTextField campo_Telefono;
    private javax.swing.JTextField campo_Telefono1;
    private javax.swing.JTextField campo_Telefono10;
    private javax.swing.JTextField campo_Telefono11;
    private javax.swing.JTextField campo_Telefono12;
    private javax.swing.JTextField campo_Telefono13;
    private javax.swing.JTextField campo_Telefono14;
    private javax.swing.JTextField campo_Telefono15;
    private javax.swing.JTextField campo_Telefono16;
    private javax.swing.JTextField campo_Telefono2;
    private javax.swing.JTextField campo_Telefono3;
    private javax.swing.JTextField campo_Telefono4;
    private javax.swing.JTextField campo_Telefono5;
    private javax.swing.JTextField campo_Telefono6;
    private javax.swing.JTextField campo_Telefono7;
    private javax.swing.JTextField campo_Telefono8;
    private javax.swing.JTextField campo_Telefono9;
    private javax.swing.JTextField campo_apellidos;
    private javax.swing.JTextField campo_correo;
    private javax.swing.JTextField campo_documento1;
    private javax.swing.JTextField campo_telefono;
    private javax.swing.JTextField campon_nombre;
    private javax.swing.JPanel contenedor_Formulario;
    private javax.swing.JPanel contenedor_Formulario1;
    private javax.swing.JPanel contenedor_Formulario10;
    private javax.swing.JPanel contenedor_Formulario11;
    private javax.swing.JPanel contenedor_Formulario12;
    private javax.swing.JPanel contenedor_Formulario13;
    private javax.swing.JPanel contenedor_Formulario14;
    private javax.swing.JPanel contenedor_Formulario15;
    private javax.swing.JPanel contenedor_Formulario16;
    private javax.swing.JPanel contenedor_Formulario17;
    private javax.swing.JPanel contenedor_Formulario2;
    private javax.swing.JPanel contenedor_Formulario3;
    private javax.swing.JPanel contenedor_Formulario4;
    private javax.swing.JPanel contenedor_Formulario5;
    private javax.swing.JPanel contenedor_Formulario6;
    private javax.swing.JPanel contenedor_Formulario7;
    private javax.swing.JPanel contenedor_Formulario8;
    private javax.swing.JPanel contenedor_Formulario9;
    private javax.swing.JLabel etiqueta_Apellidos;
    private javax.swing.JLabel etiqueta_Apellidos1;
    private javax.swing.JLabel etiqueta_Apellidos10;
    private javax.swing.JLabel etiqueta_Apellidos11;
    private javax.swing.JLabel etiqueta_Apellidos12;
    private javax.swing.JLabel etiqueta_Apellidos13;
    private javax.swing.JLabel etiqueta_Apellidos14;
    private javax.swing.JLabel etiqueta_Apellidos15;
    private javax.swing.JLabel etiqueta_Apellidos16;
    private javax.swing.JLabel etiqueta_Apellidos17;
    private javax.swing.JLabel etiqueta_Apellidos2;
    private javax.swing.JLabel etiqueta_Apellidos3;
    private javax.swing.JLabel etiqueta_Apellidos4;
    private javax.swing.JLabel etiqueta_Apellidos5;
    private javax.swing.JLabel etiqueta_Apellidos6;
    private javax.swing.JLabel etiqueta_Apellidos7;
    private javax.swing.JLabel etiqueta_Apellidos8;
    private javax.swing.JLabel etiqueta_Apellidos9;
    private javax.swing.JLabel etiqueta_Correo;
    private javax.swing.JLabel etiqueta_Correo1;
    private javax.swing.JLabel etiqueta_Correo10;
    private javax.swing.JLabel etiqueta_Correo11;
    private javax.swing.JLabel etiqueta_Correo12;
    private javax.swing.JLabel etiqueta_Correo13;
    private javax.swing.JLabel etiqueta_Correo14;
    private javax.swing.JLabel etiqueta_Correo15;
    private javax.swing.JLabel etiqueta_Correo16;
    private javax.swing.JLabel etiqueta_Correo17;
    private javax.swing.JLabel etiqueta_Correo2;
    private javax.swing.JLabel etiqueta_Correo3;
    private javax.swing.JLabel etiqueta_Correo4;
    private javax.swing.JLabel etiqueta_Correo5;
    private javax.swing.JLabel etiqueta_Correo6;
    private javax.swing.JLabel etiqueta_Correo7;
    private javax.swing.JLabel etiqueta_Correo8;
    private javax.swing.JLabel etiqueta_Correo9;
    private javax.swing.JLabel etiqueta_Documento;
    private javax.swing.JLabel etiqueta_Documento1;
    private javax.swing.JLabel etiqueta_Documento10;
    private javax.swing.JLabel etiqueta_Documento11;
    private javax.swing.JLabel etiqueta_Documento12;
    private javax.swing.JLabel etiqueta_Documento13;
    private javax.swing.JLabel etiqueta_Documento14;
    private javax.swing.JLabel etiqueta_Documento15;
    private javax.swing.JLabel etiqueta_Documento16;
    private javax.swing.JLabel etiqueta_Documento17;
    private javax.swing.JLabel etiqueta_Documento2;
    private javax.swing.JLabel etiqueta_Documento3;
    private javax.swing.JLabel etiqueta_Documento4;
    private javax.swing.JLabel etiqueta_Documento5;
    private javax.swing.JLabel etiqueta_Documento6;
    private javax.swing.JLabel etiqueta_Documento7;
    private javax.swing.JLabel etiqueta_Documento8;
    private javax.swing.JLabel etiqueta_Documento9;
    private javax.swing.JLabel etiqueta_Nombres;
    private javax.swing.JLabel etiqueta_Nombres1;
    private javax.swing.JLabel etiqueta_Nombres10;
    private javax.swing.JLabel etiqueta_Nombres11;
    private javax.swing.JLabel etiqueta_Nombres12;
    private javax.swing.JLabel etiqueta_Nombres13;
    private javax.swing.JLabel etiqueta_Nombres14;
    private javax.swing.JLabel etiqueta_Nombres15;
    private javax.swing.JLabel etiqueta_Nombres16;
    private javax.swing.JLabel etiqueta_Nombres17;
    private javax.swing.JLabel etiqueta_Nombres2;
    private javax.swing.JLabel etiqueta_Nombres3;
    private javax.swing.JLabel etiqueta_Nombres4;
    private javax.swing.JLabel etiqueta_Nombres5;
    private javax.swing.JLabel etiqueta_Nombres6;
    private javax.swing.JLabel etiqueta_Nombres7;
    private javax.swing.JLabel etiqueta_Nombres8;
    private javax.swing.JLabel etiqueta_Nombres9;
    private javax.swing.JLabel etiqueta_Telefono;
    private javax.swing.JLabel etiqueta_Telefono1;
    private javax.swing.JLabel etiqueta_Telefono10;
    private javax.swing.JLabel etiqueta_Telefono11;
    private javax.swing.JLabel etiqueta_Telefono12;
    private javax.swing.JLabel etiqueta_Telefono13;
    private javax.swing.JLabel etiqueta_Telefono14;
    private javax.swing.JLabel etiqueta_Telefono15;
    private javax.swing.JLabel etiqueta_Telefono16;
    private javax.swing.JLabel etiqueta_Telefono17;
    private javax.swing.JLabel etiqueta_Telefono2;
    private javax.swing.JLabel etiqueta_Telefono3;
    private javax.swing.JLabel etiqueta_Telefono4;
    private javax.swing.JLabel etiqueta_Telefono5;
    private javax.swing.JLabel etiqueta_Telefono6;
    private javax.swing.JLabel etiqueta_Telefono7;
    private javax.swing.JLabel etiqueta_Telefono8;
    private javax.swing.JLabel etiqueta_Telefono9;
    private javax.swing.JLabel etiqueta_texto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
