
package principal;

import utils.Persona;


public class VentanaEditar extends javax.swing.JFrame {
    
    Persona persona;
    String texto;
    TablaBotones ventana;
    
    public VentanaEditar(TablaBotones tabla,Persona persona,String texto) {
        this.ventana = tabla;
        this.texto = texto;
        this.persona = persona;
        initComponents();
        componentes();
    }

    public void componentes(){
        
        setTitle(" Edicion de Persona ");
        
        etiqueta_texto.setText(texto);
        setVisible(true);
        setLocationRelativeTo(null);
        setResizable(false);
        revalidate();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
        campo_documentoedit.setText(persona.getDocumento());
        campon_nombreedit.setText(persona.getNombres());
        campo_apellidosedit.setText(persona.getApellidos());
        campo_telefonoedit.setText(persona.getTelefono());
        campo_correoedit.setText(persona.getCorreo());
        
        ventana.imprimirPersonas();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        etiqueta_texto = new javax.swing.JLabel();
        contenedor_Formulario17 = new javax.swing.JPanel();
        etiqueta_Documento17 = new javax.swing.JLabel();
        campo_documentoedit = new javax.swing.JTextField();
        etiqueta_Nombres17 = new javax.swing.JLabel();
        campon_nombreedit = new javax.swing.JTextField();
        etiqueta_Apellidos17 = new javax.swing.JLabel();
        campo_apellidosedit = new javax.swing.JTextField();
        etiqueta_Telefono17 = new javax.swing.JLabel();
        campo_telefonoedit = new javax.swing.JTextField();
        etiqueta_Correo17 = new javax.swing.JLabel();
        campo_correoedit = new javax.swing.JTextField();
        botonCancelar = new javax.swing.JToggleButton();
        BotonAgregar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setForeground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edicion");

        etiqueta_texto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiqueta_texto.setForeground(new java.awt.Color(255, 255, 255));
        etiqueta_texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(etiqueta_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiqueta_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        contenedor_Formulario17.setBackground(new java.awt.Color(102, 204, 255));

        etiqueta_Documento17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Documento17.setText("Documento:");

        campo_documentoedit.setToolTipText("");

        etiqueta_Nombres17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Nombres17.setText("Nombres:");

        campon_nombreedit.setToolTipText("");

        etiqueta_Apellidos17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Apellidos17.setText("Apellidos:");

        campo_apellidosedit.setToolTipText("");

        etiqueta_Telefono17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Telefono17.setText("Telefono:");

        campo_telefonoedit.setToolTipText("");

        etiqueta_Correo17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Correo17.setText("Correo Elct:");

        campo_correoedit.setToolTipText("");

        botonCancelar.setBackground(new java.awt.Color(102, 102, 255));
        botonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        botonCancelar.setText("CANCELAR");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        BotonAgregar.setBackground(new java.awt.Color(0, 204, 51));
        BotonAgregar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BotonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BotonAgregar.setText("AGREGAR");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenedor_Formulario17Layout = new javax.swing.GroupLayout(contenedor_Formulario17);
        contenedor_Formulario17.setLayout(contenedor_Formulario17Layout);
        contenedor_Formulario17Layout.setHorizontalGroup(
            contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedor_Formulario17Layout.createSequentialGroup()
                .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedor_Formulario17Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenedor_Formulario17Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(BotonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenedor_Formulario17Layout.createSequentialGroup()
                                .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiqueta_Documento17, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo_documentoedit, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiqueta_Nombres17, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campon_nombreedit, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiqueta_Apellidos17, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo_apellidosedit, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(contenedor_Formulario17Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiqueta_Telefono17, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_telefonoedit, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiqueta_Correo17, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_correoedit, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contenedor_Formulario17Layout.setVerticalGroup(
            contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedor_Formulario17Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedor_Formulario17Layout.createSequentialGroup()
                            .addComponent(etiqueta_Apellidos17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(contenedor_Formulario17Layout.createSequentialGroup()
                            .addComponent(etiqueta_Nombres17)
                            .addGap(1, 1, 1)))
                    .addGroup(contenedor_Formulario17Layout.createSequentialGroup()
                        .addComponent(etiqueta_Documento17)
                        .addGap(1, 1, 1)))
                .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(campo_documentoedit)
                    .addComponent(campon_nombreedit, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_apellidosedit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiqueta_Correo17)
                    .addComponent(etiqueta_Telefono17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_telefonoedit)
                    .addComponent(campo_correoedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(contenedor_Formulario17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contenedor_Formulario17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedor_Formulario17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed
        String documento = campo_documentoedit.getText();
        String nombres = campon_nombreedit.getText();
        String apellidos = campo_apellidosedit.getText();
        String telefono = campo_telefonoedit.getText();
        String correo = campo_correoedit.getText();
          
        if( documento.equalsIgnoreCase("") && nombres.equalsIgnoreCase("")&& telefono.equalsIgnoreCase("") && apellidos.equalsIgnoreCase("")&& correo.equalsIgnoreCase("") ){
            
            Alerta ventana = new Alerta(" Todos los campos son obligatorios");
            
        }else{
           
        }
    }//GEN-LAST:event_BotonAgregarActionPerformed

     private VentanaEditar(){
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonAgregar;
    private javax.swing.JToggleButton botonCancelar;
    private javax.swing.JTextField campo_apellidosedit;
    private javax.swing.JTextField campo_correoedit;
    private javax.swing.JTextField campo_documentoedit;
    private javax.swing.JTextField campo_telefonoedit;
    private javax.swing.JTextField campon_nombreedit;
    private javax.swing.JPanel contenedor_Formulario17;
    private javax.swing.JLabel etiqueta_Apellidos17;
    private javax.swing.JLabel etiqueta_Correo17;
    private javax.swing.JLabel etiqueta_Documento17;
    private javax.swing.JLabel etiqueta_Nombres17;
    private javax.swing.JLabel etiqueta_Telefono17;
    private javax.swing.JLabel etiqueta_texto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
